from enum import StrEnum


class FailureType(StrEnum):
    NO_DOCUMENTS = "NO_DOCUMENTS"
    LOW_RELEVANCE = "LOW_RELEVANCE"
    FILTER_MISMATCH = "FILTER_MISMATCH"
    RETRIEVAL_ERROR = "RETRIEVAL_ERROR"
    AMBIGUOUS_QUERY = "AMBIGUOUS_QUERY"
